# WordPress recipe
name: wordpress

# Start with the default WordPress recipe
recipe: wordpress

proxy:
  pma:
    - pma.wordpress.lndo.site

services:
  node-cli:
    type: node:8.9

    run:
      - "cd $LANDO_MOUNT && npm install"

    globals:
      gulp-cli: "latest"

  # Override the appsever to add some environment variables and install an extra VIM package
  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get upgrade -y"

  pma:
    type: phpmyadmin
    hosts:
      - database

# Configure the WordPress recipe
config:

  php: '7.2'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: false

  conf:
    server: wordpress2.conf
    php: config/php.ini

tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli    