# WordPress recipe
name: wordpress

# Start with the default WordPress recipe
recipe: wordpress

services:
  # Override the appsever to add some environment variables and install an extra VIM package
  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get upgrade -y"
#      - "docker-php-ext-install pcntl"

# Configure the WordPress recipe
config:

  # See: https://wordpress.org/about/requirements/

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by WordPress.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in WordPress so YMMV.
  #
  # See: https://wordpress.org/about/requirements/
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.0'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://wordpress.org/about/requirements/
  #
  via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: web

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  #
  # see: https://wordpress.org/about/requirements/
  #
  database: mariadb

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use "sane defaults" for your recipe type
  conf:

    # For more information on setting these files check out the documentation
    # and examples
    #
    # Docs: https://docs.devwithlando.io/services/php.html
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
    server: wordpress2.conf
    # php: config/php.ini

    # For more information on setting these files check out the documentation
    # and examples for the relevant services:
    #
    # MySQL: https://docs.devwithlando.io/services/mysql.html
    # MariaDB: https://docs.devwithlando.io/services/mariadb.html
    # PostGres: https://docs.devwithlando.io/services/postgres.html
    #
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
    # database: config/mysql
